# Generated by Django 5.0.4 on 2025-04-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_representante_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='activation_token',
        ),
    ]
